---
title: 略奪的イノベーションと独占禁止法
date: '2024-03-22'
description: 独禁法弁護士を主な参加者とする競争法フォーラムの年次大会に参加しました。「独占禁止法と他分野の交錯領域における課題」というテーマの大会で、私が報告したのは第一部の「インクカートリッジ等プリンター訴訟３…
work: true
type: 報告
venue: 競争法フォーラム
categories:
- 報告
original-url: https://sei-shishido.themedia.jp/posts/52405552
---

独禁法弁護士を主な参加者とする[競争法フォーラム](http://www.jclf.jp/event.html)の年次大会に参加しました。「独占禁止法と他分野の交錯領域における課題」というテーマの大会で、私が報告したのは第一部の「インクカートリッジ等プリンター訴訟３件の分析」というセッションでした。個別報告をしてからパネルディスカッションという構成で、初めてかなり大きな会合でパネリストをやりました。メンバーは、モデレーターに長澤哲也先生が、個別報告とパネルに松田誠司先生、溝上武尊先生が、ととても豪華な布陣でした。先生方、本当にありがとうございました。

報告資料はresearchmapに掲載しました。[こちら](https://researchmap.jp/sei_shishido/presentations/45883979/attachment_file.pdf)からダウンロードできます。

個別報告のタイトルは「略奪的イノベーションと独占禁止法」で、主に、製品の設計変更や仕様変更が独禁法上どう取り扱われるのかをご紹介するものでした。

具体的には、イノベーションというものに対して独禁法を含む競争法がどのような考え方をとっているのかという基本原則の確認と、その原則に反して介入が必要な場合としてどのような場合があるのか、介入において法的にはどのような評価が必要なのかということを理論を中心にご紹介しました。

その中で、プリンター用消耗品に関連するリコー・ディエスジャパン事件、エレコム・ブラザー事件、エコリカ・キヤノン事件を素材に、製品の設計変更等の必要性や合理性は何のために評価されるべきなのか、評価するためにはどのような方法がありうるのか、どの要件で評価をすることが望ましいのかといったことを現時点で考えられる限りですがご報告しました。

この問題は突き詰めると、外形上は自社製品の設計や仕様を変更するに過ぎない行為に対して、独禁法がどこまで介入が許されるのか、介入するとして、裁判所の管理可能性などを考えた時にどのような法的評価枠組みがありうるのか、という点でデジタルプラットフォームやブロックチェーン、生成AIなど、最近流行りのテーマにも必ず効いてくる重要な問題です。

個人的に今回の報告で一番面白いと思っていたのは略奪的イノベーションにおける埋め合わせの論点なのですが、これまでなかなか人前でお話しする機会もなかったため、今回お話しできてとてもありがたかったです。あんまりウケてはなさそうでしたが・・・

発表が終わってからは皆様「よかったですよ」や「面白かったです」と優しく声をかけていただきましたが、本当はEUにも面白い事例が複数あり、また、国外の論文で論じられている点で触れたほうが面白い論点が他にもたくさんあったのですが時間の関係で全くご紹介できず、もっとやれることがたくさんあったのに・・・と反省しています。今後に活かします。

せっかくなので今回の報告で触れられなかった部分もフォローしたうえで、そのうちに論文として公表したいです。
